name: Perfil
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # ensure assets dir exists for generated metrics
      - name: Create assets directory
        run: |
          mkdir -p assets/metrics

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Move generated calendar to assets
        run: |
          if [ -f metrics.plugin.isocalendar.fullyear.svg ]; then
            mv metrics.plugin.isocalendar.fullyear.svg assets/metrics/
          fi

      - name: metrics-embedder action
        uses: metrics-embedder/metrics-embedder-action@v1
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         config_file: './perfil-config.yaml'
         output_file: './README.md'

      - name: Copy README to docs
        run: |
          mkdir -p docs
          cp README.md docs/index.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: |
          mkdocs build --clean

